[build]
  # The base directory (relative to the root of your repository)
  base = ""
  # The directory that contains the build output (relative to the root of your repository)
  publish = "dist"
  # Build command (e.g., for React, itâ€™s typically "npm run build")
  command = "npm run build"


